import { Document, Page, Text, View, Image } from '@react-pdf/renderer';
import { styles } from './PDFStyles';
import { AssessmentResult } from '@/types/assessment';

interface AssessmentReportProps {
  data: AssessmentResult;
  chartImage?: string; // Base64 image of the radar chart
}

export default function AssessmentReport({ data, chartImage }: AssessmentReportProps) {
  const { archetype, overallScore, axisScores, dimensionScores, blockers, companyData } = data;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.headerRow}>
            <Text style={styles.logo}>AI MATURITY INDEX</Text>
            <Text style={styles.date}>{new Date().toLocaleDateString()}</Text>
          </View>
          <Text style={styles.title}>AI Readiness Report</Text>
          <Text style={styles.subtitle}>Prepared for {companyData.name}</Text>
        </View>

        {/* Archetype Section */}
        <View style={styles.archetypeCard}>
          <Text style={styles.archetypeLabel}>YOUR ARCHETYPE</Text>
          <Text style={styles.archetypeName}>{archetype.name}</Text>
          <Text style={styles.archetypeHook}>"{archetype.hook}"</Text>
          <Text style={styles.archetypeDesc}>{archetype.description}</Text>
        </View>

        {/* Score Grid */}
        <View style={styles.scoreGrid}>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreLabel}>Overall Readiness</Text>
            <Text style={styles.scoreValue}>{overallScore}/100</Text>
          </View>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreLabel}>Strategic Vision</Text>
            <Text style={styles.scoreValue}>{axisScores.vision}/100</Text>
          </View>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreLabel}>Operational Capability</Text>
            <Text style={styles.scoreValue}>{axisScores.ops}/100</Text>
          </View>
        </View>

        {/* Radar Chart (Image) */}
        {chartImage && (
          <View style={{ height: 300, marginBottom: 20 }}>
            <Image src={chartImage} style={{ width: '100%', height: '100%', objectFit: 'contain' }} />
          </View>
        )}

        {/* Dimensions */}
        <Text style={styles.sectionTitle}>Dimension Breakdown</Text>
        <View style={{ marginBottom: 30 }}>
          {dimensionScores.map((dim, i) => (
            <View key={i} style={styles.dimensionRow}>
              <Text style={styles.dimensionName}>{dim.dimension}</Text>
              <Text style={styles.dimensionScore}>{dim.score}/100</Text>
            </View>
          ))}
        </View>

        {/* Top Blockers */}
        <Text style={styles.sectionTitle}>Critical Blockers</Text>
        <View>
          {blockers.slice(0, 3).map((blocker, i) => (
            <View key={i} style={styles.blockerItem}>
              <Text style={styles.blockerTitle}>{blocker.issue}</Text>
              <Text style={styles.blockerText}>
                Impact: {blocker.impact} • Cost: {blocker.costRange}
              </Text>
            </View>
          ))}
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Generated by John Ellison AI Transformation • john-ellison.com
          </Text>
        </View>
      </Page>
    </Document>
  );
}
